# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.22.0"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    cocoapods
    
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"





lane :weilv do
    # match(
    #   git_url: "",
    #   type: "adhoc",
    #   app_identifier: "com.weiding.wang"
    #  )
         # snapshot
         currentTime = Time.new.strftime("%Y-%m-%d-%H-%M")
         ipaName = "SIT-#{currentTime}.ipa"
    gym(
      scheme: "WeiLvDJS",
      export_method:"ad-hoc",
      silent:true,
      # archive_path:"./build/sit/",
      output_directory:"./build/sit/",
      output_name:ipaName
     ) # Build your app - more options available
     # sh "your_script.sh"
    #deliver(force: true)
    # frameit
    # You can also use other beta testing services here (run `fastlane actions`)
  end 





  lane :beta do
    # match(type: "appstore") # more information: https://codesigning.guide
    gym(scheme: "WeiLvDJS") # Build your app - more options available
    pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"

  
  lane :release do
    # match(type: "appstore")
    # snapshot
    gym(scheme: "WeiLvDJS") # Build your app - more options available
    deliver(force: true)
    # frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )

    pgyer(api_key: "461917d6194a6ffe1f617e9c7e2bea96", user_key: "2af872946ad7dd27597fc741d94086e1")
    
    
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
